{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vexil.fullname" . }}-operator
  namespace: {{ include "vexil.namespace" . }}
  labels:
    {{- include "vexil.operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "vexil.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vexil.operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.operator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "vexil.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "vexil.serviceAccountName" . }}
      {{- with .Values.operator.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: operator
          image: {{ include "vexil.operator.image" . }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
            {{- if .Values.operator.leaderElect }}
            - --leader-elect
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          {{- with .Values.operator.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.operator.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
